[[module]]
repo = "github.com/cjtoolkit/ignition/generate"
tag = "c0064d719d1437e77f395f851ca768207d5f3fff"
binPath = "tools"
installs = [
	"debugflag",
	"easymock"
]

[[module]]
repo = "github.com/golang/mock"
tag = "v1.4.3"
binPath = "tools"
installs = [
	"mockgen"
]

[[module]]
repo = "github.com/cjtoolkit/embedder"
tag = "v1.0.0"
binPath = "tools"
installs = [
	"."
]